brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - peco/peco
    - motemen/ghq
    - caskroom/cask
    - starhoshi/starhoshicask
    - homebrew/science
    - sanemat/font

  install_packages:
    - brew-cask
    - the_silver_searcher
    - coreutils
    - findutils
    - zsh
    - bash
    - vim
    - tmux
    - git
    - mercurial
    - bzr
    - svn
    - tig
    - ghq
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - readline
    - markdown
    - jq
    - peco
    - ctags
    - rbenv
    - ruby-build
    - opencv
    - htop-osx
    - ssh-copy-id
    - watch
    - gotags
    - httpie
    - pyenv

  install_apps:
    # lancher app
    - alfred
    - google-chrome
    - appcleaner
    # security soft
    - avast
    # simple editor
    - coteditor
    # programing code refarence
    - dash
    # mac native docker
    - docker
    # keybind mapper
    - karabiner
    - slack
    - virtualbox
    - iterm2
    # graph editor
    # can not install yed.
    # - yed
    - 1password
    # markdown editor
    - abricotine
    # move and git tool
    - recordit
    # photo editor
    - acorn
    # Video, Audio and Images converter
    - adapter
    # Tiling window manager for OS X along the lines of xmonad and i3.
    - amethyst
    # view animated gif
    - animated-gif-quicklook
    # customize your desktop with great flexibility
    - geektool
    - unity
    - robomongo
    - google-web-designer
    - gitbook-editor
    - gitter
    - xbench
    - fontstand
