brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - peco/peco
    - motemen/ghq
    - caskroom/cask
    - starhoshi/starhoshicask
    - peco/peco
    - homebrew/science
    - sanemat/font

  install_packages:
    - the_silver_searcher
    - brew-cask
    - coreutils
    - findutils
    - zsh
    - bash
    - vim
    - tmux
    - git
    - hub
    - tig
    - ghq
    - imagemagick
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - libyaml
    - readline
    - markdown
    - jq
    - peco
    - ctags
    - rbenv
    - ruby-build
    - opencv
    - htop-osx
    - mercurial
    - ssh-copy-id
    - mongodb
    - watch
    - gotags
    - httpie
    - the_silver_searcher

  install_apps:
    - alfred
    - google-chrome
    - iterm2
    - slack
    - google-japanese-ime
    - appcleaner
    - kitematic
    - recordit
    - coteditor
    - karabiner
    - nmap
    - xquartz
